R1= input("Enter Quiz Number 1:")
R2= input("Enter Quiz Number 2")
R3= input("Enter Quiz Number 3")
R4= input("Enter Quiz Number 4")
R5= input("Enter Quiz Number 5")
R6= input("Enter Quiz Number 6")
R7= input("Enter Quiz Number 7")
Markslist=[R1,R2,R3,R4,R5,R6,R7]
Markslist.sort()
print(Markslist)